Feature/refactor mapper loader
Ensembl/ensembl-xref pull request #66
Opened 2019-01-16 13:12 UTC by markmcdowall

## Description

Addition of the Mapper::Loader module to replace the XrefLoader.pm module from the previous xref pipeline. The changes include more tests and documentation for all the new functions.

## Benefits

Separated out the major update() function into testable chunks so that changes can be tested more easily

## Possible Drawbacks

Much of the code is the same, so there are probably places where there can be further work done to refine the code or the flow. This was an exercise to separate out the functionality into separate units.

## Testing

There are now lots more tests

2019-01-16 15:38 UTC, nerdstrike requested changes
Ok... the tests and factorisation are good. There are a smattering of typos and a few oddities caused by Python encroachment. A nice parting gift from Mark.

I have not checked the thoroughness of the testing / edge-case handling.

Whomever is on this next should look into shrinking BaseAdaptor, as it's getting ridiculous. Also, there are situations where the core API could be used for non-bulk operations.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_valid_source_id_to_external_db_id {
You might consider this having a cache for subsequent requests, although I'm not sure if it's ever used more than once per Hive process. Perhaps it's better if it's simple.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +=head2 get_insert_identity_xref
Confusing method name

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_insert_dependent_xref {
As above, this reads poorly in isolation

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +               could be unmapped. These shoudld be used to describe the xrefs
Typo

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +
I think BaseAdaptor is too big at this stage.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +use DBI;
This can go now. Data::Dumper above also.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  Arg [3]    : hashref - $analyss_ids
Typo

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  Return type: Hashref
Returntype seems to be undef

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  Return type: Hashref
This also appears to be out of date

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      print "PROBLEM:: what type is $xref_handle{'type'}\n";
More colons than a digesting cow

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  return @xref_list;
Careful here. Passing a list by value can be expensive with large numbers of values.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  return @xref_list;
As above, beware. We pass references to avoid triggering a copy on all list elements

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  my $sth = $self->core->dbc->prepare('SELECT db_name, external_db_id FROM external_db');
We have a perfectly good DBEntryAdaptor for this kind of thing

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      $analysis_id= %{ $analysis_ids }{$xref_handle{'ensembl_object_type'}};
I wouldn't normally use this idiom. I prefer $hashref->{$key}, and I would need convincing that %{ $hashref }->{$key} is equivalent.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +    $self->core()->dbc()->sql_helper()->execute_update(
You can probably do this with the AnalysisAdaptor too.

2019-01-16 15:38 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  return %results;
Again, returning in list context. You're copying the hash entire. Good for preventing side effects, bad for memory efficiency.

2019-01-17 15:09 UTC, markmcdowall commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_valid_source_id_to_external_db_id {
There are a couple of times that this happens, it came about so that the functions could be run in isolation as these functions were going to be run in the `update()` function. We could have functions like include a test to see if it has been pre-generated already and store within the object. This could probably be done in future work?

2019-01-17 16:21 UTC, nerdstrike commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_valid_source_id_to_external_db_id {
Absolutely. Functional trumps performance tuning.

2019-01-17 17:37 UTC, markmcdowall commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +
I would tend to agree. There are probably places where there could be consolidation of functions, but for this exercise I was trying to just break down the functionality. This might also have to be an exercise for a future coding sprint.

2019-01-25 17:25 UTC, mkszuba requested changes
Could use a few more changes... Nothing particularly serious though.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +=head2 get_insert_checksum_xref
Another confusing method name.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +    WHERE xref_id IN ( @{[join',', ('?') x @{$xref_list}]} )
The second part of this line is really confusing and hard to read.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_insert_direct_xref_low_priority {
Another confusing method name.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +sub get_insert_dependent_xref_low_priority {
Yet another confiusing method name... Actually, let's just say *all* the names in this package which begin with _get_insert_ are confusing to me, just in case I do not flag all of them during the review.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  foreach my $key (keys %desc_failed){
A space before the curly brace, perhaps?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  # remove xref, object_xref, identity_xref, depenedent_xref, go_xref, unmapped_object, (interpro???), external_synonym, projections.
What is this line for?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  # my $xref_dbi = $self->xref->dbc;
No commented-out code, please. In my experience, commented-out code has a tendency to rot, not to mention the fact most code analysers do not scan it.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  print "xref offset is $xref_offset, object_xref offset is $object_xref_offset\n";
Do we need this?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  my $last_acc= 0;
Could use a space before the =.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +    if( !defined $name_to_external_db_id{ $dependent_handle{'dbname'} } ){
Space after _if_?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      $analysis_id= %{ $analysis_ids }{$xref_handle{'ensembl_object_type'}};
Seconded. At the very least, _$hashref->{key}_ reads more easily than _%{hashref}{key}_.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      $analysis_id = %{ $analysis_ids }{ $xref_handle{'ensembl_object_type'} };
Ditto.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      $identity_xref_handle{'analysis_ids'}{ $identity_xref_handle{'ensembl_type'} },
I wonder if this could be made a bit more readable.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  # $dependent_sth->bind_columns(\$xref_id, \$acc, \$label, \$version, \$desc, \$info, \$object_xref_id, \$ensembl_id, \$ensembl_type, \$master_xref_id);
Commented-out code.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +      if ( defined $dependent_xref_handle{'master_xref_id'} ) { # need to sort this out for FlyBase since there are EMBL direct entries from the GFF and dependent xrefs from Uniprot
I would move the comment to a separate line or lines, this one is long enough even without it present.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +        # $add_dependent_xref_sth->execute(($object_xref_id+$object_xref_offset), ($master_xref_id+$xref_offset), ($xref_id+$xref_offset) );
Commented-out code.

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +    print "WARNING:: for $ex_id $err_master_count problem master xrefs\nExamples are :-\t";
Is there a point in just printing this, with no attempt to draw the user's attention?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  my $insert_sth = $dbc->prepare( $insert_sql );
I take it abstaining from using _prepare_cached()_ in this module is intentional?

2019-01-25 17:25 UTC, mkszuba commented on modules/Bio/EnsEMBL/Xref/Mapper/Loader.pm
> +  return %externalname_to_externalid;
As @nerdstrike has already pointed out elsewhere, there are issues with not passing complex data structures by reference. Moreover, there are many other functions in this module which already use references for that so it might pay to be consistent.

2019-01-25 17:25 UTC, mkszuba commented on modules/t/baseadaptor.t
> +use Data::Dumper;
I would say that if we do not use this (or any other) module in a package, better not to import it.

2019-01-25 17:25 UTC, mkszuba commented on modules/t/loader.t
> +use Data::Dumper;
I would say that if we do not use this (or any other) module in a package, better not to import it.

2019-01-25 17:25 UTC, mkszuba commented on modules/t/loader_mapped_xrefs.t
> +use Data::Dumper;
I would say that if we do not use this (or any other) module in a package, better not to import it.

2019-01-25 17:25 UTC, mkszuba commented on modules/t/loader_unmapped_xrefs.t
> +use Data::Dumper;
I would say that if we do not use this (or any other) module in a package, better not to import it.

2019-01-25 17:25 UTC, mkszuba commented on modules/t/loader_update.t
> +use Data::Dumper;
I would say that if we do not use this (or any other) module in a package, better not to import it.

2019-05-03 10:24 UTC, wbazant commented on modules/Bio/EnsEMBL/Xref/DBSQL/BaseAdaptor.pm
> +      'update_desc' => 1
Also: please add a comma at the end of the line 492. Then if you add another line between 492 and 493, it will show up clearly in the diff - this is as important as aligning the arrows and all-round good Perl style.

2019-05-15 12:16 UTC, markmcdowall commented on .gitignore
> +local/
This is a side effect of using carton for handling the dependencies. It creates this directory.

2019-09-26 14:15 UTC, s-mm commented
@mkszuba @nerdstrike What do we do with this PR?

2019-09-26 14:16 UTC, mkszuba commented
Hah, I have completely forgotten about. Seeing as we are not going to backport mapper code to _ensembl_, we might as well just drop this PR.

2019-09-26 14:16 UTC, closed without merging